spring.application.name=graphql_test
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=app
spring.datasource.password=app_password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
